version: "3"
services:
  postgres-db:
    image: "postgres:11-alpine"
    environment:
      POSTGRES_DB: cursotdd
      POSTGRES_USER: demostenes
      POSTGRES_PASSWORD: abc123
    ports:
      - "5432:5432"
